# Generated by Django 6.0.1 on 2026-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='features',
            name='name',
            field=models.CharField(default='', max_length=69),
        ),
    ]
